README-task-master.md, README.md, scripts/init.js
When running: ```npx claude-task-init``` it doesn't work
We should use the updated ```npx task-master-ai``` instead
=> chore(config): fix typos

assets/env.example, bin/task-master.js, package.json, scripts/init.js, scripts/modules/ai-services.js, scripts/modules/commands.js, scripts/modules/task-manager.js, scripts/modules/ui.js, scripts/task-complexity-report.json, tasks/tasks.json, tests/unit/task-manager.test.js
This commit improves the 'parse-prd' command and ensures consistency in CLI help messages across different entry points.
**Changes:**
- **Improved 'parse-prd' command:**
- Made the `file` argument optional for the `parse-prd` command in both `commands.js` and `bin/task-master.js`.
- Added a helpful message box with usage instructions when `parse-prd` is called without a PRD file, instead of showing a generic error.
- **Consistent CLI Help:**
- Standardized the help display in `bin/task-master.js` to directly use the `displayHelp()` and `displayBanner()` functions from `ui.js`, ensuring consistent help output with `scripts/dev.js`.
- Added code to `commands.js` to display the banner and help message when `task-master` or `dev.js` is run without any arguments.
- **Description Consistency:** …
=> Fix: Improve 'parse-prd' command and CLI help consistency

.cursor/rules/commands.mdc, bin/task-master.js, scripts/dev.js, tasks/task_024.txt
Error detection for camelCase flags:
- When users try to use camelCase flags like --numTasks or --taskId, they receive a clear error message suggesting the kebab-case alternative
- The error messages are helpful and include an example
Proper kebab-case handling:
- Commands that use proper kebab-case flags like --num-tasks work correctly
- Multiple options work together, like --id=24 --num=4 --research
Default option handling:
- Default options from Commander are passed correctly, like --file=tasks/tasks.json
- Options are only added if not already specified by the user
Positional arguments:
- Positional arguments like file paths are correctly passed to the underlying script
Command execution:
- Actual commands work end-to-end, as shown with the show and list commands
- Complex output …
=> fix: camelCase detection mechanism in global CLI

.cursor/rules/commands.mdc, .cursor/rules/new_features.mdc, bin/task-master.js, package.json, scripts/modules/commands.js, scripts/sample-prd.txt
- Fixed CLI wrapper to convert camelCase options to kebab-case when passing to dev.js
- Added explicit support for --input option in parse-prd command
- Updated commands.mdc to clarify Commander.js camelCase/kebab-case behavior
=> fix: ensure CLI correctly handles kebab-case options

.changeset/seven-numbers-juggle.md, mcp-server/src/tools/addTask.js
- Fix `projectRoot not defined` when trying to add task from the mcp
=> fix: addTask mcp tool not working

.changeset/salty-walls-find.md, package-lock.json, package.json
Fix `npm install` breaking due to a non-existent package
=> fix: npm i breaking

.changeset/silly-horses-grin.md, .cursor/rules/taskmaster.mdc
Adjusts the taskmaster.mdc rules for `init` and `parse-prd` so the LLM correctly reaches for the next steps rather than trying to reinitialize or access tasks not yet created until PRD has been parsed
In the init part of the rules I now mention
`**Important:** Once complete, you *MUST* parse a prd in order to generate tasks. There will be no tasks files until then. The next step after initializing should be to create a PRD using the example PRD in scripts/example_prd.txt. `
In the parse-prd part of the rules I now mention
`**Important:** This MCP tool makes AI calls and can take up to a minute to complete. Please inform users to hang tight while the operation is in progress. If the user does not have a PRD, suggest discussing their idea and then use the example PRD in …
=> Rules adjust post init

.changeset/brave-doors-open.md, .changeset/two-bats-smoke.md, .cursor/rules/tests.mdc, mcp-server/src/core/direct-functions/add-task.js, mcp-server/src/tools/add-task.js, package.json, scripts/modules/commands.js, scripts/modules/task-manager.js, scripts/modules/utils.js, tasks/task_056.txt, tasks/task_057.txt, tasks/task_058.txt, tasks/task_059.txt, tests/fixture/test-tasks.json, tests/setup.js, tests/unit/commands.test.js, tests/unit/mcp/tools/add-task.test.js
- Add support for --title/-t and --description/-d flags in add-task command
- Fix validation for manual creation mode (title + description)
- Implement proper testing for both prompt and manual creation modes
- Update testing documentation with Commander.js testing best practices
- Add guidance on handling variable hoisting and module initialization issues
Fully tested, all green
Changeset: brave-doors-open.md
=> fix(commands): implement manual creation mode for add-task command

.cursor/mcp.json, mcp-server/src/core/direct-functions/initialize-project-direct.js, mcp-server/src/core/direct-functions/parse-prd.js, mcp-server/src/tools/parse-prd.js
Refactors parse-prd MCP tool to properly handle project root and path resolution, fixing the 'Input file not found: /scripts/prd.txt' error.
Key changes include: Made projectRoot a required parameter, prioritized args.projectRoot over session-derived paths, added validation to prevent parsing in invalid directories (/, home dir), improved error handling with detailed messages, and added creation of output directory if needed.
This resolves issues similar to those fixed in initialize-project, where the tool was incorrectly resolving paths when session context was incomplete.
=> feat(mcp): Fix parse-prd tool path resolution

README.md, docs/tutorial.md
- Users who don't have the package `task-master-ai` installed, can't use npx -y task-master-mcp...
=> fix: README bug not showing precise instructions

.changeset/chubby-moose-stay.md, mcp-server/src/tools/update-subtask.js, mcp-server/src/tools/update-task.js, mcp-server/src/tools/update.js
Updates the parameter descriptions for update, update-task and update-subtask to ensure the MCP server correctly reaches for the right update command based on what is being updated -- all tasks, one task, or a subtask.
=> fix(update/update-task/update-subtask): 

README.md
The discord badge in the readme wasn't a link, causing GitHub to just open the original image on click. I wrapped it in the same link that was in the badge url `https://discord.gg/2ms58QJjqp`
=> Fix discord badge in readme

scripts/modules/task-manager/update-task-by-id.js, scripts/modules/task-manager/update-tasks.js
Refactors the JSON array parsing logic within
in .
The previous logic primarily relied on extracting content from markdown code blocks (json or javascript), which proved brittle when the AI response included comments or non-JSON text within the block, leading to parsing errors for the  command.
This change modifies the parsing strategy to first attempt extracting content directly between the outermost '[' and ']' brackets. This is more robust as it targets the expected array structure directly. If bracket extraction fails, it falls back to looking for a strict json code block, then prefix stripping, before attempting a raw parse.
This approach aligns with the successful parsing strategy used for single-object responses in  and resolves the
parsing errors previously observed with the …
=> fix(update-tasks): Improve AI response parsing for 'update' command

.changeset/many-wasps-sell.md, .changeset/pre.json, package-lock.json, package.json, scripts/modules/commands.js, scripts/modules/ui.js, src/utils/getVersion.js
This pull request resolves issues where the tool's version was displayed as 'unknown' in the main banner and in the update availability notification.
**Changes Made:**
- Modified `displayBanner` in `scripts/modules/ui.js` to correctly read `package.json` relative to its own script location using `import.meta.url`. This ensures the main banner displays the accurate installed version.
- Modified `checkForUpdate` in `scripts/modules/commands.js` to also use `import.meta.url` for resolving its `package.json` path. This fixes the 'unknown' version in the "Update Available!" message.
- Restored a missing closing curly brace in `scripts/modules/ui.js` which was causing a `SyntaxError`.
These changes ensure consistent and correct version reporting throughout the tool.
- Closes #432
=> Fix: Correct version resolution for banner and update check

assets/roocode/.roomodes
fix `mdode` to `mode` in .roomodes
=> fix: roomodes typo

README.md, scripts/modules/supported-models.json
The current .json config shown on the README has a bunch of extra commas, which are not valid:
The correct version would remove the last comma after the last entry of `env`, as well as the unnecessary ones between curly brackets:
I didn't test the VS Code option, but it also seems incorrect with the commas:
=> Fix Cursor & Windsurf `mcpServers` json example

.changeset/modern-cats-pick.md, scripts/modules/commands.js, scripts/modules/config-manager.js, scripts/modules/supported-models.json, src/ai-providers/bedrock.js, tests/unit/config-manager.test.js
- Change error to warning when AWS credentials are missing in environment
- Allow fallback to system configuration (aws config files or instance profiles)
- Remove hardcoded region and profile parameters in Bedrock client
- Add Claude 3.7 Sonnet and DeepSeek R1 model definitions for Bedrock
- Update config manager to properly handle Bedrock provider
=> fix(bedrock): improve AWS credential handling and add model definitions

README.md
Adds a troubleshooting note about removing --package flag when "0 tools enabled" appears in MCP settings.
- Fixes #761
- Discussed in #767
=> readme: add troubleshooting note for MCP tools not working

.changeset/swift-squids-sip.md, assets/roocode/.roo/rules-architect/architect-rules, assets/roocode/.roo/rules-ask/ask-rules, assets/roocode/.roo/rules-code/code-rules, assets/roocode/.roo/rules-debug/debug-rules, assets/roocode/.roo/rules-orchestrator/orchestrator-rules, assets/roocode/.roo/rules-test/test-rules
Updated all references to Roo Code "Boomerang" mode to "Orchestrator".  
This puts code in line with current Roo Code conventions.
=> Rename Roo Code "Boomerang" role to "Orchestrator"

.changeset/icy-dryers-hunt.md, scripts/init.js, scripts/modules/commands.js, src/utils/rule-transformer.js
Call rules interactive setup during taskmaster init.
Does not get called when --rules flag is used to specify rule profiles for init
=> Call rules interactive setup during init

docs/configuration.md, docs/models.md, scripts/modules/supported-models.json
- Add detailed Azure OpenAI configuration section with prerequisites, authentication, and setup options
- Include both global and per-model baseURL configuration examples
- Add comprehensive troubleshooting guide for common Azure OpenAI issues
- Update environment variables section with Azure OpenAI examples
- Add Azure OpenAI models to all model tables (Main, Fallback)
- Include prominent Azure configuration example in main documentation
- Fix azureBaseURL format to use correct Azure OpenAI endpoint structure
=> docs: Add comprehensive Azure OpenAI configuration documentation

.changeset/mean-papayas-share.md, .gitignore, mcp-server/src/core/direct-functions/initialize-project.js, mcp-server/src/tools/initialize-project.js
Updates MCP `initialize_project` to default to Cursor profile instead of installing all rule profiles when no profiles specified.
- **MCP initialization**: Defaults to `["cursor"]` rules when none specified
- **CLI behavior**: Unchanged - runs interactive rules setup when no profiles specified
- **Impact**: Cleaner project directory without extra rule profiles installed by default
=> Default to Cursor profile for MCP init when no rules specified

.changeset/major-dogs-admire.md, src/utils/manage-gitignore.js, tests/unit/manage-gitignore.test.js
Fixes an issue where .gitignore files created during project initialization were missing the standard trailing newline.
- Updated `src/utils/manage-gitignore.js` to append `\n` when writing .gitignore files
- Affects both new file creation and existing file merging paths
- Ensures .gitignore files follow POSIX text file standards
- Prevents potential issues with tools that expect files to end with newlines
- No breaking changes or behavioral differences beyond the newline addition
=> fix: .gitignore missing trailing newline during project initialization

.changeset/tame-vans-throw.md, scripts/modules/task-manager/expand-task.js
This PR fixes a critical issue where subtask generation fails on gemini-2.5-pro unless explicitly prompted to `return 'details' field as a string not an object`
=> fix: Subtask generation fails on gemini-2.5-pro

.changeset/chubby-needles-beam.md, mcp-server/src/core/direct-functions/update-tasks.js, mcp-server/src/tools/update.js, scripts/modules/task-manager/update-tasks.js, tests/unit/scripts/modules/task-manager/update-tasks.test.js
Fix critical bug in bulk update functionality that was corrupting tasks.json when working with tagged task lists. The issue was in the `update-tasks.js` file where the `writeJSON` call was missing the required `projectRoot` and `tag` parameters, causing data corruption and task disappearance in tagged contexts.
Closes #854
The `updateTasks` function in `scripts/modules/task-manager/update-tasks.js` was calling `writeJSON(filepath, data)` without the required `projectRoot` and `tag` parameters. When `writeJSON` tries to handle tagged data without proper context, it corrupts the file structure causing tasks to disappear from tasks.json.
1. **Core Function Fix** (`scripts/modules/task-manager/update-tasks.js`):
- Added `getCurrentTag` import for proper tag handling
- Updated function …
=> fix: prevent tag corruption in bulk updates

.changeset/smooth-ants-live.md, README-task-master.md, docs/command-reference.md, docs/configuration.md, mcp-server/src/core/direct-functions/parse-prd.js, mcp-server/src/tools/parse-prd.js, scripts/modules/commands.js, scripts/modules/config-manager.js, scripts/modules/task-manager/expand-task.js, scripts/modules/task-manager/parse-prd.js, tests/unit/config-manager.test.js, tests/unit/scripts/modules/task-manager/expand-task.test.js, tests/unit/scripts/modules/task-manager/parse-prd.test.js
This PR allows the hard definition of the number of tasks / subtasks generated by 'parse-prd' and 'expand-task' commands to be relaxed by using '0' value in the config or command parameter
- Not entirely sure about adding conditional logic to the prompts, but there is already some there...
- This PR is not compatible with #882 - which is an overhaul of the prompting system
=> Feat: Added automatic determination of task number based on complexity

.changeset/cuddly-baboons-invent.md, package-lock.json, package.json
This PR updates the `ai-sdk-provider-gemini-cli` dependency from version 0.0.3 to 0.0.4 to resolve authentication compatibility issues and improve the developer experience when using the Gemini CLI provider.
- **Dependency Update**: Updated `ai-sdk-provider-gemini-cli` from `^0.0.3` to `^0.0.4`
- **Package Lock**: Updated `package-lock.json` with new dependency versions
- **Changeset**: Added changeset for proper release tracking
- ✅ Fixed authentication compatibility issues with Google auth
- ✅ Resolved "Unsupported authType: undefined" runtime errors
- ✅ Updated `@google/gemini-cli-core` dependency from 0.1.7 to 0.1.9
- ✅ Updated `LOGIN_WITH_GOOGLE_PERSONAL` to `LOGIN_WITH_GOOGLE`
- ✅ Added support for `'api-key'` auth type alongside existing `'gemini-api-key'`
- ✅ Maintained backward …
=> fix: Update ai-sdk-provider-gemini-cli to 0.0.4 for improved authentication
