eyaltoledano/claude-task-master

- scripts/modules/commands.js
- scripts/modules/ui.js
Slight refactor moving numTasks and outputPath to top with the other variables.  Eliminates duplication, and keeps us from having to implement check twice. 
Resolves #65
> Added confirmation for task overwrite if tasks.json exists.

- tests/unit/task-manager.test.js
Lost my tests on the PR somehow. Repushing to next
> Add test for confirmation prompt

- .changeset/red-lights-mix.md
- .github/workflows/release.yml
- Fix github actions trying to create npm releases on next branch push
> fix: github actions

- .changeset/all-parks-sort.md
- scripts/modules/ai-services.js
- scripts/modules/task-manager.js
- tests/unit/ai-services.test.js
**Fixed "NaN" Error with --all Option:**
- Added parameter validation and defaults in parseSubtasksFromText
- Properly handles missing or undefined startId and expectedCount parameters
- Prevents invalid ID comparisons that could result in NaN values
**Fixed JSON Formatting Error with Research Enabled:**
- Standardized response handling between Claude and Perplexity AI modes
- Added proper error catching during JSON parsing
- Improved validation of AI responses with type checking to ensure valid structures
**Added Error Reporting for Failed Tasks:**
- The command now tracks and reports both successes and failures
- Final summary shows how many tasks were successfully expanded and how many failed
- Users can see exactly which tasks had issues
The code now correctly processes tasks whether …
> fix(expand-all): resolve NaN errors and improve error reporting

- README.md
- docs/tutorial.md
- mcp-server/src/tools/index.js
- package.json
- scripts/init.js
- Remove unnecessary logs breaking MCP
- Remove task-master-mcp-server command
- Change command to npx -y --package task-master-ai task-master-mcp
> fix: MCP config and commands

- .changeset/happy-snails-train.md
- mcp-server/src/tools/analyze.js
- tests/fixture/test-tasks.json
- tests/unit/mcp/tools/analyze-complexity.test.js
- tests/unit/task-manager.test.js
- Changed threshold parameter to coerce.number() with min/max validation
- Fixed "Invalid type for parameter threshold" error
- Added proper test implementation to avoid real API calls
- Added tests for threshold parameter validation
This ensures proper handling of valid threshold inputs while rejecting 
invalid values, with comprehensive test coverage.
> fix(analyze-complexity): fix threshold parameter validation and testing

- .changeset/brave-seas-pull.md
- bin/task-master.js
> fix: shebang issues

- .changeset/poor-ducks-fly.md
- scripts/modules/ai-services.js
Added a bit of chain of thought.
> Prompt engineering prd breakdown

- .changeset/calm-ways-visit.md
- .github/workflows/release.yml
- README.md
- docs/tutorial.md
- scripts/modules/dependency-manager.js
The README will be the DEATH-OF-ME.md
> fix: dependency manager & friend fixes

- .changeset/calm-ways-visit.md
- .github/workflows/release.yml
- README.md
- docs/tutorial.md
- scripts/modules/dependency-manager.js
- added support for roo code prompts and roles etc
- added resources to MCP
- web interface for task voerview
> Support for Roo code, MCP additions, Web interface.

- .changeset/violet-papayas-see.md
- scripts/modules/ui.js
- scripts/test-claude.js
> Fix --tasks to --num-tasks in ui (fixes #324)

- README.md
Update to use pretty link, requested in #325
Also changed alt text to just 'Discord'
> Update Discord badge to pretty link

- .changeset/tricky-wombats-spend.md
- mcp-server/src/core/direct-functions/update-tasks.js
> fix: updateTask enableSilentMode is not defined

- .changeset/forty-plums-stay.md
- docs/configuration.md
- package-lock.json
- scripts/modules/ai-services-unified.js
- scripts/modules/config-manager.js
- src/ai-providers/anthropic.js
- src/ai-providers/google.js
- src/ai-providers/openai.js
- src/ai-providers/openrouter.js
- src/ai-providers/perplexity.js
- src/ai-providers/xai.js
- tests/unit/ai-services-unified.test.js
- .taskmasterconfig now supports a baseUrl field per model role (main, research, fallback), allowing endpoint overrides for any provider.
- Closes #287
- Closes #360
> feat: implement baseUrls

- .changeset/six-cloths-happen.md
- mcp-server/src/core/direct-functions/complexity-report.js
- mcp-server/src/core/direct-functions/list-tasks.js
- mcp-server/src/core/direct-functions/next-task.js
- mcp-server/src/core/direct-functions/show-task.js
> fix: remove cache from list-tasks and next-task mcp calls

- .changeset/twenty-plums-act.md
- mcp-server/src/core/direct-functions/set-task-status.js
- mcp-server/src/tools/set-task-status.js
Fixes https://github.com/eyaltoledano/claude-task-master/issues/235
> Add next task to set status for mcp server

- .cursor/rules/taskmaster.mdc
Fixed the typo in the Api keys
> Fixed the Typo in cursor rules Issue:#675

- .changeset/curly-dragons-design.md
- .changeset/eleven-news-check.md
- mcp-server/src/core/direct-functions/update-tasks.js
- package-lock.json
- package.json
- src/utils/path-utils.js
- improve findTasksPath function
- fix `update` MCP tool
- Upgrade fastmcp from v1 to v2
- No breaking changes since we're using stdio, and the breaking changes included sse
> fix: `Update` MCP tool

- .changeset/sour-lions-check.md
- mcp-server/src/tools/initialize-project.js
- scripts/init.js
- src/utils/manage-gitignore.js
Re-implement default behavior of storing tasks in Git (reverted in PR 743)
> fix: Store tasks in Git by default

- .changeset/flat-geckos-enjoy.md
- docs/models.md
- package-lock.json
- scripts/modules/supported-models.json
**Context:** Prior to this change (ie v0.18.0), I was only able to get the following models to work with Task Master:
```
us.anthropic.claude-3-5-haiku-20241022-v1:0
us.anthropic.claude-3-7-sonnet-20250219-v1:0
```
Pricing information is from: https://aws.amazon.com/bedrock/pricing/ (looking at Anthropic in `us-east-1`).
I used the following `.taskmaster/config.json`:
```json
{
"models": {
"main": {
"provider": "bedrock",
"modelId": "us.anthropic.claude-sonnet-4-20250514-v1:0",
"maxTokens": 50000,
"temperature": 0.2
},
"research": {
"provider": "bedrock",
"modelId": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
"maxTokens": 65536,
"temperature": 0.1
},
"fallback": {
"provider": "bedrock",
"modelId": "us.anthropic.claude-3-5-haiku-20241022-v1:0",
"maxTokens": 128000,
"temperature": 0.2
} …
```
> Support for Additional Anthropic Models on Bedrock

- .changeset/wicked-rats-hide.md
- scripts/modules/commands.js
- src/utils/create-mcp-config.js
- src/utils/rule-transformer.js
The `rules` command was using `process.cwd()` for project root detection, while other commands like `models`, `list`, and `add-task` use the more reliable `findProjectRoot()` function. This inconsistency caused the `rules` command to potentially fail when run from subdirectories, while other commands work correctly.
1. **Updated `rules` command** to use `findProjectRoot()` with proper error handling
2. **Standardized parameter naming** across all related functions for consistency:
- Updated `convertAllRulesToProfileRules()` and `removeProfileRules()` in `rule-transformer.js`
- Updated `setupMCPConfiguration()` and `removeTaskMasterMCPConfiguration()` in `create-mcp-config.js`
- Changed parameter name from `projectDir` to `projectRoot` throughout
- Changed from `const projectDir = …
> Fix `rules` command to use reliable project root detection like other commands

- mcp-server/src/core/direct-functions/remove-task.js
- scripts/modules/task-manager/response-language.js
- Fix remove-task bug with mcp
- Fix response-language using old config file .taskmaster
> fix: issues with release

- docs/providers/gemini-cli.md
- src/ai-providers/gemini-cli.js
This PR fixes incorrect authentication command references in the Gemini CLI provider documentation.
The documentation and code comments contained references to a non-existent `gemini auth login` command, which was causing confusion for users trying to authenticate with the Gemini CLI provider.
- Updated `docs/providers/gemini-cli.md` to use the correct `gemini` command for authentication
- Clarified that users should launch the interactive CLI and select "Login with Google" for OAuth
- Removed erroneous `gemini auth login` comment from `src/ai-providers/gemini-cli.js`
- Enhanced documentation with clearer authentication instructions and troubleshooting steps
- ✅ Fixed authentication command from `gemini auth login` to `gemini`
- ✅ Added clearer OAuth authentication instructions
- ✅ …
> docs: fix gemini-cli authentication documentation

- .changeset/grok-4-support.md
- docs/models.md
- scripts/modules/supported-models.json
This PR adds support for the newly released xAI Grok 4 model to Task Master.
- Add grok-4 model configuration to `supported-models.json` with $3/$15 per 1M token pricing
- Enable main, fallback, and research roles for grok-4
- Update models documentation to include grok-4 in all three tables
- Add changeset for release notes
- **Model ID**: `grok-4` (official model name: `grok-4-0709`)
- **Context window**: 256,000 tokens (configured max_tokens: 131,072 to match other xAI models)
- **Pricing**: $3.00 per million input tokens, $15.00 per million output tokens
- **Capabilities**: Function calling, structured outputs, reasoning
- Manually tested with xAI API key
- All existing tests pass
- No changes to core functionality
The model aliases (`grok-4-0709`, `grok-4-latest`) are supported by …
> feat: add support for xAI Grok 4 model

- mcp-server/src/core/direct-functions/add-task.js
- scripts/modules/task-manager/add-task.js
- remove task-generation
- fix mcp add-task generation in manual mode
> fix: add-task fixes
